/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        txtNumEnt1.requestFocusInWindow();
        cmdConvertir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumEnt1 = new javax.swing.JTextField();
        txtNumEnt2 = new javax.swing.JTextField();
        txtNumEnt3 = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtNumerador1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtDenominador1 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        txtNumerador2 = new javax.swing.JTextField();
        txtDenominador2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNumerador3 = new javax.swing.JTextField();
        txtDenominador3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmdConvertir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Operaciones con numeros mixto a fraccionario");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 50));

        jLabel2.setText("Numero entero 2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel5.setText("Numero entero 1");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtNumEnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumEnt1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumEnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));
        jPanel3.add(txtNumEnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 70, -1));

        txtNumEnt3.setEditable(false);
        txtNumEnt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumEnt3ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumEnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 70, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 70, -1));

        txtNumerador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerador1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 10));
        jPanel3.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, -1));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumar", "Restar", "Multiplicar", "Dividir" }));
        jPanel3.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 70, -1));

        txtNumerador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerador2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 60, -1));
        jPanel3.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 60, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 60, 10));

        txtNumerador3.setEditable(false);
        txtNumerador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerador3ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 60, -1));

        txtDenominador3.setEditable(false);
        jPanel3.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, 10));

        jLabel4.setText("=");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        cmdConvertir.setText("Convertir a Mixto");
        cmdConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConvertirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel6.setText("=");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(472, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumEnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumEnt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumEnt1ActionPerformed

    private void txtNumerador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador1ActionPerformed

    private void txtNumerador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador2ActionPerformed

    private void txtNumerador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador3ActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        
        int op;
        int ent1,num1,den1;
        int ent2,num2,den2;
        int ent3,num3,den3;
        NumMixto M1,M2,M3=null;
        
        cmdConvertir.setEnabled(true);
        op = cmbOperacion.getSelectedIndex();
        ent1 = Integer.parseInt(txtNumEnt1.getText());
        num1 = Integer.parseInt(txtNumerador1.getText());
        den1 = Integer.parseInt(txtDenominador1.getText());
        ent2 = Integer.parseInt(txtNumEnt2.getText());
        num2 = Integer.parseInt(txtNumerador2.getText());
        den2 = Integer.parseInt(txtDenominador2.getText());
        
        num1=ent1*den1+num1;
        num2=den2*den2+num2;
                
        
        try{
        M1 = new NumMixto(num1,den1);
        M2 = new NumMixto(num2,den2);
        switch (op){
            case 0:
                M3 = M1.Sumar(M2);
                break;
            case 1:
                M3 = M1.restar(M2);
                break;
            case 2:
                M3 = M1.multiplicar(M2);
                break;
            case 3:
                M3 = M1.dividir(M2);
                break;
        }
        ent3 = M3.getNumerador() / M3.getDenominador();
        txtNumEnt3.setText(""+ent3);
        txtNumerador3.setText(""+M3.getNumerador() % M3.getDenominador());
        txtDenominador3.setText(""+M3.getDenominador());
        
    }
    catch (DenominadorCeroException e){
        JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    catch (NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Campos vacios por favor ingrese los digitos", "ERROR", JOptionPane.ERROR_MESSAGE);
        txtNumEnt1.setText("");
        txtNumEnt2.setText("");
        txtNumEnt3.setText("");
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtNumEnt1.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);
    
   
    }
        
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
      
        txtNumEnt1.setText("");
        txtNumEnt2.setText("");
        txtNumEnt3.setText("");
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtNumEnt1.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);
        cmdConvertir.setEnabled(false);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConvertirActionPerformed
    int Num,Den,Ent;
    
    
    Ent=Integer.parseInt(txtNumEnt3.getText());
    Num=Integer.parseInt(txtNumerador3.getText());
    Den=Integer.parseInt(txtDenominador3.getText());
    
    Num = Ent*Den+Num;
    txtNumerador3.setText(String.valueOf(Num));
    txtNumerador3.setText(String.valueOf(Den));
    txtNumEnt3.setText("");
    cmdConvertir.setEnabled(false);
    }//GEN-LAST:event_cmdConvertirActionPerformed

    private void txtNumEnt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumEnt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumEnt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtNumEnt1;
    private javax.swing.JTextField txtNumEnt2;
    private javax.swing.JTextField txtNumEnt3;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    // End of variables declaration//GEN-END:variables
}
